language: node_js
node_js:
  - "6"

services:
  - mongodb

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.2-precise

    packages:
      - g++-4.8
      - mongodb-org-server

cache:
  directories:
    - node_modules
script:
  - cd $TRAVIS_BUILD_DIR/api-server && npm test
  - cd $TRAVIS_BUILD_DIR/app && npm test

install: 
  - cd $TRAVIS_BUILD_DIR/api-server && npm install
  - cd $TRAVIS_BUILD_DIR/app && npm install
      